### ISSUE TITLE
Problems under Redmine 4.2

### ISSUE THREAD

**Issue by alterdaemon** [dr-consit/redmine_app_notifications#3]
1. I had setup faye propely in different ways as per instruction (via thin, rackup, service) - it works, I see connection

2. problem is I am always getting (Your Faye server is unreachable)

3. I am also gettting the problem #2 using this fork (which at least doesn't present problem with missing methods or SSL)

https://github.com/kporras07/redmine_app_notifications/tree/redmine-4-compatibility

5. in your fork I am getting:

5. 1. SSLError 
```
Completed 500 Internal Server Error in 1190ms (ActiveRecord: 207.6ms)
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: wrong version number):
plugins/redmine_app_notifications/app/models/app_notification.rb:22:in `deliver'
```
4. 2. NoMethodError 
```
Completed 500 Internal Server Error in 490ms (ActiveRecord: 119.2ms)
NoMethodError (undefined method `parse_mentions' for #Journal:0x00007f8acaf001c0):
plugins/redmine_app_notifications/lib/app_notifications_journals_patch.rb:38:in create_app_notifications_after_create_journal' app/models/journal.rb:100:in save'
```

**Comment by DavidRobinsonDk** [comment]
Please try this branch: https://github.com/dr-consit/redmine_app_notifications/tree/Fix_Issue_%231 and see if it fixes your issues.

**Comment by alterdaemon** [comment]
thx, I tried.

no SSL error but still no connection with faye from the plugin.
I've got question: Should I use SSL configuration and do I need to use https?

here's my faye.ru:
```
require 'faye'
Faye::WebSocket.load_adapter('thin')

bayeux = Faye::RackAdapter.new(:mount => '/faye', :timeout => 25)
run bayeux
```

I tried to run for https
thin start -R faye.ru -p 9292 --ssl --ssl-key-file  Key.key --ssl-cert-file  cert.crt  --ssl-disable-verify --ssl-version TLSv1_2
but I've got
```
:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42
```

Could you please provide me with example how you configure faye using thin so the plugin can connect to it? (thin is running on the same server)

**Comment by alterdaemon** [comment]
and if I try to run
```
thin start -R faye.ru -p 9292 --ssl  --ssl-cert-file cert.crt --ssl-disable-verify --ssl-version TLSv1_2
```
or
```
thin start -R faye.ru -p 9292 --ssl --ssl-cert-file cert.pem  --ssl-disable-verify --ssl-version TLSv1_2
```
I get
```
SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:2283:
```

**Comment by alterdaemon** [comment]
Now it works all right after many tries. I had to use server domain name in the plugin settings, not just ip.
Thank you very much.
I will provide more feedback in the future :)
